### ISSUE TITLE
Playback server not available.

### ISSUE THREAD

**Issue by avatarx51** [d8ahazard/Phlex#114]
Hi
I am running into a recent issue where Phlex does not find my Plex server, so when i ask to play a movie or show it says its not in my library but it really is this was working fine last week.  Under Phlex settings tab i tried to test connection it says "ERROR: HOME not available"

see logs below, any help is appreciated

Tue, 25 Jul 2017 16:54:20 +0200 - api.php::testConnection
URL is: https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:32400?X-Plex-Token=XXXXXXXXXXXXXXXXXXXX

**Comment by Cyberchaos** [comment]
I'm having this exact same issue and it was working fine yesterday.

**Comment by d8ahazard** [comment]
Hello.  I suspect this may be due to some changes I made with the way some variables are stored.  Please give a pull of the latest commits and see if that helps.  

If not, try deleting "dlist" and any entry in config.ini.php starting with "plexServer".  Log out and in, and see if that helps.

If still no-go, check out the Settings Menu > Plex.  There's a new toggle for "Disable Plex.Direct".  Enable this, then manually rescan devices from the dropdown on the main screen.  

If *STILL* nojoy, send me an email with full files for your Phlex.log an Phlex_error.log files.

**Comment by XmemphistoX** [comment]
I just did what d8ahazard recommended and it worked for me.

**Comment by avatarx51** [comment]
Thanks! its working now!
