### ISSUE TITLE
Flex TV: I'm working on that

### ISSUE THREAD

**Issue by Cyberchaos** [d8ahazard/Phlex#115]
Note, I sent d8ahazard a similar email, but posting it here in case anyone can help too.

I'm going through first time setup for the second time (I was in the middle of setup when FlexTV went down on Google the first time), and everything seems to work fine, except when I ask Flex via Google Home to do anything - ask what's on deck, play X etc. The vocal response is always "I'll try to do that" or something. If I check in my Phlex interface, it's trying to respond with the correct JSON string - "Here you go", "Here's on deck items" etc. However, the vocal prompt always bugs out. If I ask it to play something, it bugs out but still plays the episode soon after etc, which really kills the vibe of using it as a voice interface.

I have a feeling this has to do with a messed up API token. I've unlinked and relinked to no avail as was suggested here: https://github.com/d8ahazard/Phlex/issues/59.

Overall, this thing is absolutely fantastic work, I just wish stuff would work for me out of the box, you know?

Does anyone have any ideas?

**Comment by d8ahazard** [comment]
I've fixed some issues with both the client and server, please lmk if you're still having issues.

**Comment by Cyberchaos** [comment]
I downloaded the latest version, overwrote etc, but I'm still seeing the same problems. I've noticed through use that small commands like "play" or "pause" or "stop" will fire back with a voice command saying "Sure", but things like "What's on deck" or "Play Once Upon A Time (2011)" etc are still coming back with "It's taking a little longer than expected, but I'll try to do that for you", so no real change there.

**Comment by Cyberchaos** [comment]
Now it's even worse - nothing is working at all. Every response is "I'll try to do that", and nothing is even feeding into Phlex to be trying to process the JSON strings.

**Comment by abwyatt** [comment]
Hi d8ahazard. I'm a newcomer to Phlex. Managed to setup and it's working of sorts. I'm a lifetime PlexPass user and recently got on the Google Home bandwagon. Phlex really has a lot of potential and I am willing to help test. 

Just wanted to chip in on Cyberchaos contribution to say that I am also having exactly the same experience. Every movie playback will receive the 'It's taking a little longer than expected, but I'll try to do that for you' feedback. The movie will launch, sometimes continuing to play but sometimes stopping altogether. Play, pause commands are fine.

I am using the casting option - Chromecast on the TV. No Plex Direct is not enabled since I am able to connect.

Happy to contribute to testing.  

Andrew

**Comment by Cyberchaos** [comment]
Bump. Finally got Flex vaguely working again but still working on that for everything, despite casting etc working to a degree.
