### ISSUE TITLE
Can't find /Phlex

### ISSUE THREAD

**Issue by phila213** [d8ahazard/Phlex#125]
Hi,

Thanks for all the great work.  This looks and sounds like just the app I was after.

I've installed Phlex on a Synology NAS using Docker and am able to connect to the server with no problems.  I can connect using both the internal and external addresses / ports and it all seems tobe working however when I try to load external URL it return 404 Not Found.

The home page (index.php) appears to work fine but as soon as I replace that with /Phlex I receive the error.

Has anyone seen this error before and can anyone give me a hint as to where my issue might lie ?

Thanks in advance.

Regards,
Phil

**Comment by d8ahazard** [comment]
You'll need to set up a reverse-proxy so that you can talk to the outside world.  In Synology CP, go to "Application Portal", "Reverse Proxy".  

Click "Create".

Put in whatever description you want.  

For the source, set up something like "phlex.mydomain.com" for the hostname, port 80.  

For destination, set "localhost" and "5666" for hostname and port.  

Or - 443 and 5667 for ports if you want to use HTTPS, but then you need to add "phlex.mydomain.com" to the Subject Alternative Name (SAN) in the https cert you would need to get from LetsEncrypt in control panel > Security > Certificates.  Once you have the cert, you need to click "configure" and set it to be the default cert for the service "phlex.mydomain.com".  

So, you don't need the /Phlex extension on docker - just host:port.

Also, instead of reverse proxying - you could just forward port 5666 from your syno box to 5666 at your public IP on your router.  

Either way - I've got a syno box and this running in docker, I know the above will work.  As such, I'm going to close this issue.  If you require more help, feel free to comment and re-open.
