### ISSUE TITLE
Manually specify IP of Plex server

### ISSUE THREAD

**Issue by jfjallid** [d8ahazard/Phlex#129]
So I'm running Plex in a docker container in host mode such that the plex container uses the ip address of the host but also has access to other network adapters including some used for docker. The auto discovery feature in Phlex retrieves an ip address that the plex server can not be reached through because the Plex seems to publish all available ip addresses including non-physical interfaces.

Can I manually specify which IP address and port the server is reachable though and which should be used for media playback? If not, it would be a nice feature.

**Comment by d8ahazard** [comment]
I'd prefer to just figure out what local IP it's using, and make sure to not assign that as the connection URI to use for the server.  The idea is that it should test the connection for each device on a rescan to ensure that the URL selection is working.  

If that's not behaving correctly, then the proper solution is to fix it - not statically assign device info.  ;)

**Comment by jfjallid** [comment]
Yes, if it can figure out which IP addresses are local and exclude those that can not be used to reach the plex server instance, that would be better. 

It seems as it always uses one of the docker address e.g. 172.17.0.1 and never tries any of the other addresses.

**Comment by JoooostB** [comment]
@jfjallid Have you figured this out? I'm running both Phlex as Plex in a Docker environment as well now; but Phlex isn't able to find my local server, while it finds my friends ones (external) just fine.

**Comment by jfjallid** [comment]
@JoooostB No, but I specify the IP of my Plex server manually in the config.ini.php file as a temporary workaround. However, at times there is still some problem with Phlex responding that it will try to do something and then nothing happens.

**Comment by MDamon** [comment]
Same issue here.. Showing 2 of several plex servers, none of which are mine unfortunately.

**Comment by d8ahazard** [comment]
Hi, thanks for the feedback.

This issue has either been fixed in the current /beta branch, or is slated for revisal/revision in the forthcoming V2 release.

As such, I'll be closing this issue to help focus on outstanding issues and features yet to be addressed in the new codebase.

Feel free to follow the progress in the /beta branch, and be sure to get set up by adding the new cast plugin to your local Plex server.

https://github.com/d8ahazard/Cast.bundle

Keep an eye on the forum for the release of FlexTV 2.0!
