### ISSUE TITLE
Todo: Add switch to disable ATV devices in cast discovery (Taken Over TV)

### ISSUE THREAD

**Issue by TerpZone** [d8ahazard/Phlex#130]
Just recently installed Phlex and it seems pretty awesome except that when I back out of Plex after I'm done  it keeps pulling Plex back up; I had to change the CC to be Plex Web in order to get it to stop.  So far I've only tested casting to my Android TV.

**Comment by teshiburu2017** [comment]
Im having a similar issue here as well @TerpZone it seems that when i try to set itup to control my Nvidia shield it chooses to use the cast feature, and not the actual plex app...

**Comment by cjackson234** [comment]
Same issue here, but I just restarted the docker to get it to stop.

**Comment by d8ahazard** [comment]
@TerpZone Typically, if you have Android TV, you should just use the normal Plex integration, and not the cast device of it.  I'll make a mental note to add a switch to remove ATV devices from the cast list, the main reason I haven't already is because I use it for testing...

**Comment by d8ahazard** [comment]
Hehey, my testers!

Hi, thanks for the feedback.

This issue has either been fixed in the current /beta branch, or is slated for revisal/revision in the forthcoming V2 release.

As such, I'll be closing this issue to help focus on outstanding issues and features yet to be addressed in the new codebase.

Feel free to follow the progress in the /beta branch, and be sure to get set up by adding the new cast plugin to your local Plex server.

https://github.com/d8ahazard/Cast.bundle

Keep an eye on the forum for the release of FlexTV 2.0!
