### ISSUE TITLE
Apple TV 4 not showing up when scanning for devices

### ISSUE THREAD

**Issue by n1ck3** [d8ahazard/Phlex#140]
Hi!

I saw you had an issue earlier that had been closed. I am experiencing the same type of issue though.

The Apple TV 4 is not listed as an available player.
So far I see the following as players:
- PLEX WEB (CHROME)

Just as the in the previous issue, I know the apple tv app is advertising as a player as I can see it as an available player on the plex.tv web app.

Is this a known issue and is there anything I can do? Can I provide any additional information to help debug this?

Cheers

**Comment by d8ahazard** [comment]
Unfortunately, I don't have an Apple TV, so I don't have any way of building this.  My *guess* is it's using MDNS/multicast or maybe just Bonjour to talk to it, but without a test device, I'm unable to capture the necessary data to make it work reliably.  

Despite my aversion to Apple products, if you or anybody else out there with an interest would like to donate a device so I can add support for it, send me an email at my donate address, listed in the readme.

If I get a donated device, I'll re-open this...otherwise, it'll be closed.
