### ISSUE TITLE
Cannot Link to Google

### ISSUE THREAD

**Issue by kwmiller67** [d8ahazard/Phlex#144]
I am using XAMPP and PHP version xampp-win32-7.1.9-0-VC14.  I have configured everything correctly and I have verified that I can hit my site from outside of my network.  When I try to link my Amazon account I have no issues, but when I try to link my Goggle account, it gives me the following error.

Unable to connect to Client at http://xx.xx.xx.xx:80/Phlex, please check the setting for 'Public Address' in the Phlex UI.

I am extremely baffled have tried everything I know.  I am not a coder but I now a bit about computers and networks.  Can someone tell me why I cannot link to my google account?

Thanks
kwmiller67

**Comment by jasongi** [comment]
Some ISPs block port 80 incoming. I would change that and update your port forwarding on your router and in the public address field.

**Comment by kwmiller67** [comment]
I originally had the port set to 90 and it was also giving me the same error.  If my ISP was blocking port 80, why would I be able to link to Amazon?  Is there a port you would suggest I change it to?

Thanks

**Comment by jasongi** [comment]
Generally it's better to use a port above 1024 for these types of things to avoid clashing with other applications. Are you sure you can connect from an outside network (e.g disconnect from your Wi-Fi on your phone and try connecting via your public address)?

**Comment by kwmiller67** [comment]
I will  change the port to something above 1024.  I did connect from another outside network not associated with my wifi and was able to use my public ip:port to connect and I got the Phlex login screen.

Since I can connect to Amazon, might the issue be with something in my Goggle settings?  I have disabled 2 factor authentication.

Thanks for help Jasongi!

**Comment by kwmiller67** [comment]
SOLVED

Jasongi I figured out what my issue was.  It seems that the certificate had expired (phlexserver.cookiehigh.us).  Once I figured that out I did a google search on cookiehigh.us and it brought me to this page

https://certificatedetails.com/a84a6a63047dddbae6d139b7a64565eff3a8eca1/374cd82078c6df47fbe96f708c2f58339b8/phlexserver.cookiehigh.us

Half way down the page, ther is a link called "Issue Certificate URL"  I clicked the link and it downloaded a new cert.  After I installed the cert, I was able to complete the Phlex process and it took me to the Google login page.

Thanks for your help!!

**Comment by d8ahazard** [comment]
Well that's not good!  I'll have to update the cert.  Thanks for pointing
this out!!

**Comment by d8ahazard** [comment]
Wait, I just double-checked, and my cert is good till december...and should
auto-renew:

https://phlexserver.cookiehigh.us/

**Comment by d8ahazard** [comment]
Okay, so, this is odd.  The link says "Issuing Certificate URL".  That's a
cert that tells your computer that Let'sEncrypt is who they say they are,
and they can be trusted.  Why your computer isn't trusting them is the
ultimate question.  What OS are you using?

**Comment by kwmiller67** [comment]
I am  running Windows 10.  It may be my setup.

**Comment by kwmiller67** [comment]
so I changed my public IP address and I want to relink my public IP with your servers.  When I click on link to google, it goes back to the same screen I had before "please check the setting for 'Public Address' in the Phlex UI.".  

I can talk to my google home to Flex TV but I never received a link in GH.  Is there anyway I could send you my public IP and API and you could add it to the servers?  Is there a way to unlink my other Public IP from your servers?  Am I talking to much like a newbie at this?  Let me know if you can guide me please.

Thanks
kwmiller67

**Comment by ammmze** [comment]
I'm also struggling with this. I've verified mine works by testing from my phone with wifi turned off. Mine does force HTTPS though, so not sure if that matters. I'm using a certificate from Let's Encrypt.

**Comment by ammmze** [comment]
Yea...must have been the HTTPS thing. I setup port forwarding for phlex to bypass my traefik proxy (which enforces HTTPS) for now and that seems to work. Kinda disappointing that it can't communicate over HTTPS.

**Comment by d8ahazard** [comment]
The app itself will work fine over https, else I wouldn't have a toggle to
force it.  You'll just need to forward port 443 or whatever your webserver
uses for https, and include that in the "public address" field when you
link your URL.

**Comment by ammmze** [comment]
Okay...you're right, it does work on HTTPS provided i'm using the HTTPS provided by Phlex. But I can't seem to get it to work using SSL termination in traefik proxy.

Does it only work with the cert provided by phlex?

Here's a sequence diagram showing what i'd prefer (the top half) vs what actually works (the bottom half). 
![cdraw](https://user-images.githubusercontent.com/203336/32074590-c13d5b0e-ba4e-11e7-8716-120bdf19075b.png)

**Comment by d8ahazard** [comment]
Unfortunately, the top request (443-5666) won't work.  You'd be trying to
run encrypted traffic onto a non-encrypted port on the webserver, which
makes things "not happy".

You *can* forward port 5667 on your internal network to 443 at
phlex.example.com, and just use https://phlex.example.com as your final
public URL.  That's how https works, that's how it's designed to work.

As far as the cert - phlex doesn't provide one.  I have mine reverse
proxied on my nas so that all traffic to 443 at example.com goes to 443 on
my NAS's internal IP.  I have a cert installed on the NAS that has "
phlex.example.com" as a SAN.  Then set up reverse proxy on the NAS so that
https://phlex.example.com:443 forwards to https://phlex.docker.com:5667.
The ins and outs may vary for your setup, but this is how it should be
configured.

**Comment by ammmze** [comment]
Thanks for your example. I'll have to dig into it more because it *should* work. It's called "SSL Termination". It's common practice with load balancer/proxy server. It works just fine for the Phlex UI, Sonarr, Radarr, etc. I'll update as I figure more out.

**Comment by ammmze** [comment]
Okay...I figured it out ... I just had to take off the trailing forward slash. I had assumed it was necessary because the default url that was in there had it. But I guess we know what happens when you assume :p. So `https://phlex.example.com` instead of `https://phlex.example.com/`. When the trailing slash was in there, the call from `phlexserver.cookiehigh.us` looked like this in my proxy (traefik)

```
proxy_1         | 35.165.111.168 - - [26/Oct/2017:23:30:01 +0000] "GET //api.php?testclient&apiToken=<omitted> HTTP/1.1" 400 173 - - 279 "phlex" "http://192.168.0.10:5666" 0ms
```

Then in my phlex instance it looked like this...
```
172.19.0.8 - - [26/Oct/2017:16:29:03 -0700] "GET http://api.php?testclient&apiToken=<omitted> HTTP/1.1" 400 173 "-" "-"
```

And obviously `http://api.php` is not correct. Not sure why it works with the slash and an alternate port like 5667. I had attempted with explicitly adding 443 for the port but no luck there.
