### ISSUE TITLE
Problem with Phlex getting response from Radarr

### ISSUE THREAD

**Issue by Cyclopean** [d8ahazard/Phlex#145]
So, I have phlex set up perfectly and it works great with sonarr. But I have a small issue with Radarr.

When I ask Phlex (from google home) to play a movie that I don't have it asks if I want to download it (using radarr obviously).  If I say yes google home responds with an error that it was unable to parse the response and I need to update phlex.  But when I check my download client (deluge) it works perfectly and the movie is downloading.  How do I fix this?  I have the newest version of everything include phlex.

**Comment by d8ahazard** [comment]
Give it a whirl now.  I had some error checking that wasn't working correctly, you should get a response now.

**Comment by d8ahazard** [comment]
Hi, thanks for the feedback.

This issue has either been fixed in the current /beta branch, or is slated for revisal/revision in the forthcoming V2 release.

As such, I'll be closing this issue to help focus on outstanding issues and features yet to be addressed in the new codebase.

Feel free to follow the progress in the /beta branch, and be sure to get set up by adding the new cast plugin to your local Plex server.

https://github.com/d8ahazard/Cast.bundle

Keep an eye on the forum for the release of FlexTV 2.0!
