### ISSUE TITLE
not finding chromecast

### ISSUE THREAD

**Issue by slasse** [d8ahazard/Phlex#149]
Hi,

i am also having some troubles finding my chromecast,

Account link: Google assistant
Install type: Unraid Docker

i can easily find and use the chromecast from my phone or webbrowser
Phlex does find my tablet

can you point me in a direction to look?
i updated the container today

**Comment by ArchonMegalon** [comment]
This helped me:

MDNS/Multicast/Cast Discovery

Chromecasts are fun devices. They're fun for this project because they use Multicast DNS (Aka Bonjour, Aka Avahii, Aka Zeroconf) in order to talk to one another on a home network.

On a very basic home network with just one router and everything connected via wifi, MDNS usually just works. Usually.

However, there are thousands of different router manufactureres, and thousands of different network configurations that could play a part in how well your cast devices will talk with Phlex.

If you are experiencing issues with cast devices not showing up in Phlex, you should first verify that the php sockets module is installed and enabled. If you used XAMPP, it should be included, you just need to edit your php.ini file to enable it.

If you used an alternative webserver option, google it.

If sockets are enabled and you STILL can't see all of your cast devices, I would suggest looking in the web UI for your router and looking for any setting related to "multicast filtering", "bonjour","or MDNS discovery". Most of them should support it, it may just need to be enabled.

**Comment by ThrDev** [comment]
Make sure your unraid docker image is running in host mode.

**Comment by d8ahazard** [comment]
Hi, thanks for the feedback.

This issue has either been fixed in the current /beta branch, or is slated for revisal/revision in the forthcoming V2 release.

As such, I'll be closing this issue to help focus on outstanding issues and features yet to be addressed in the new codebase.

Feel free to follow the progress in the /beta branch, and be sure to get set up by adding the new cast plugin to your local Plex server.

https://github.com/d8ahazard/Cast.bundle

Keep an eye on the forum for the release of FlexTV 2.0!
