### ISSUE TITLE
PlexKodiConnect Not Being Detected

### ISSUE THREAD

**Issue by Monstar316** [d8ahazard/Phlex#161]
Hello,

Phlex is unable to pick up PlexKodiConnect in list of players but will show both my Chromecasts:
![image](https://user-images.githubusercontent.com/16082971/31771960-d97ca5e0-b4d5-11e7-9cb9-e19d793f30d1.png)

I've tried re-scanning for devices and restarting the host server but still nothing.

Plex is picking up Kodi but not sure if that is the Kodi app itself or PlexKodiConnect it is picking up.
![image](https://user-images.githubusercontent.com/16082971/31772088-532c7488-b4d6-11e7-8773-fc3575a2e2ad.png)

If you need any logs from me, let me know.

**Comment by d8ahazard** [comment]
Do you have multiple servers?  For PKK, you need to select the server that you have PKK pointed at in Kodi.

**Comment by Monstar316** [comment]
No. Just the one server I have.

**Comment by abrenoch** [comment]
Just a follow-up: I dug thru the code a little bit to find the XML phlex is requesting from plex (`https://plex.tv/api/resources?includeHttps=0&includeRelay=0&X-Plex-Token=xxxxx`). It appears my kodi instance is listed as a device, but presents no `Connection` tags within it as the other discovered devices (which looking at the code appears to be imperative).

Any thoughts on why this might be? I tried troubleshooting the plugin itself, but I'm having trouble tracking down relevant info...

**Comment by d8ahazard** [comment]
Hi, thanks for the feedback.

This issue has either been fixed in the current /beta branch, or is slated for revisal/revision in the forthcoming V2 release.

As such, I'll be closing this issue to help focus on outstanding issues and features yet to be addressed in the new codebase.

Feel free to follow the progress in the /beta branch, and be sure to get set up by adding the new cast plugin to your local Plex server.

https://github.com/d8ahazard/Cast.bundle

Keep an eye on the forum for the release of FlexTV 2.0!
