### ISSUE TITLE
Can't play by album or artist

### ISSUE THREAD

**Issue by MrEmielH** [d8ahazard/Phlex#164]
When i ask phlex to play just 1 song it works perfect. However when i ask to play an album or an artist phlex says "okay, playing ..." but the playback doesn't start on the player.

![phlex](https://user-images.githubusercontent.com/7473543/31832532-a52ca900-b5c7-11e7-910c-725a17f4e746.PNG)

**Comment by Graaber** [comment]
Hello !
Did you find a fix to solve your problem.
I have the same issue with a very large library (100000 tracks)
Regards

**Comment by d8ahazard** [comment]
Hi, thanks for the feedback.

This issue has either been fixed in the current /beta branch, or is slated for revisal/revision in the forthcoming V2 release.

As such, I'll be closing this issue to help focus on outstanding issues and features yet to be addressed in the new codebase.

Feel free to follow the progress in the /beta branch, and be sure to get set up by adding the new cast plugin to your local Plex server.

https://github.com/d8ahazard/Cast.bundle

Keep an eye on the forum for the release of FlexTV 2.0!
