### ISSUE TITLE
Phlex doesn't recognize the word "the" when requesting a show.

### ISSUE THREAD

**Issue by groan** [d8ahazard/Phlex#166]
Try to have Phlex play "The Flash" or The Deuce" and it will tell you it can't find Deuce or it can't find Flash.

I even tried to have it play the "the deuce". It just drops all "the"s.

**Comment by mtompkins** [comment]
I have an interesting outlier that is sort of relevant.

NYPD Blue - old series ... has an Episode with a name of "Big Ban Theory".
There is of course our more recent TBBT of which I'm a fan.

I can't use "Phlex TV play The Big Bang Theory" .. it only spins up this single episode. I just hope none of my neighbors could hear me as I tried every sort of variant to get it to play. They'll never believe me.

**Comment by d8ahazard** [comment]
Hi, thanks for the feedback.

This issue has either been fixed in the current /beta branch, or is slated for revisal/revision in the forthcoming V2 release.

As such, I'll be closing this issue to help focus on outstanding issues and features yet to be addressed in the new codebase.

Feel free to follow the progress in the /beta branch, and be sure to get set up by adding the new cast plugin to your local Plex server.

https://github.com/d8ahazard/Cast.bundle

Keep an eye on the forum for the release of FlexTV 2.0!
