### ISSUE TITLE
Problem with Phlex sending Radarr requested movie

### ISSUE THREAD

**Issue by Wraithers** [d8ahazard/Phlex#168]
Using both linked Google Account and IFTTT, Phlex receives the command to download the movie (tested with Star Trek III: Search for Spock and others) and the logs always start with `This movie already exists` from `api.php::radarrDownload` and a response of `"status": "SUCCESS: Already in searcher."` in the JSON.

Of course the movie doesn't show up in the `Wanted` or `Activity` sections of Radarr with the profile I selected, and the connection to Radarr is tested and working as well.

On what OS are you running Phlex?
Win10

Are you using a new instance of XAMPP, or an existing webserver?
XAMPP

If using an existing Webserver, have you ensured the proper modules are enabled and installed, and that PHP can read and write to the /Phlex directory?
N/A

If you're having issues communicating with a specific instance of Plex/Couchpotato/Sonarr/etc. - tell me the OS you're running that app on.
Win10 (same system as Plex and Phlex) / Radarr

Is Phlex using http or https?
http

**Comment by teejo75** [comment]
This might be an issue with your radarr install.
I've successfully asked Phlex to download movies via radarr.

**Comment by d8ahazard** [comment]
Hi, thanks for the feedback.

This issue has either been fixed in the current /beta branch, or is slated for revisal/revision in the forthcoming V2 release.

As such, I'll be closing this issue to help focus on outstanding issues and features yet to be addressed in the new codebase.

Feel free to follow the progress in the /beta branch, and be sure to get set up by adding the new cast plugin to your local Plex server.

https://github.com/d8ahazard/Cast.bundle

Keep an eye on the forum for the release of FlexTV 2.0!
