### ISSUE TITLE
Unable to change Player or Server

### ISSUE THREAD

**Issue by dill651** [d8ahazard/Phlex#169]
Hello I can't seem to get Phlex to change Server or Player using either voice (GH) or typing into the "How can I Help?" bar. I will get a response saying it has been changed, look on the GUI and its changed there but I'm still connected to whatever I was connected to before the command. 

I can change Server and Player from the GUI by manually changing them in the settings. 

Plex is running on a freenas machine and phlex is running on a separate windows 10 machine with XAMPP installed a couple days ago.

**Comment by craigmiller160** [comment]
I second this issue. I just installed Phlex, and I'm using it with my brand new Google Home mini. I experience the same issue. All other Phlex commands work perfectly.

Running Phlex and Plex on the same Ubuntu 16.01 desktop.

**Comment by bobpaul** [comment]
What revision are you using? It's working for me on `1f0b000f69` (Dec 5)

**Comment by bobpaul** [comment]
I updated today to `9aec9ff9bb93` (Jan 3) and the "Change Player" command no-longer seems to work.

**Comment by bobpaul** [comment]
I used git bisect and found changing players was broken by `8259c7af0a` (Dec 6)

**Comment by d8ahazard** [comment]
Hi, thanks for the feedback.

This issue has either been fixed in the current /beta branch, or is slated for revisal/revision in the forthcoming V2 release.

As such, I'll be closing this issue to help focus on outstanding issues and features yet to be addressed in the new codebase.

Feel free to follow the progress in the /beta branch, and be sure to get set up by adding the new cast plugin to your local Plex server.

https://github.com/d8ahazard/Cast.bundle

Keep an eye on the forum for the release of FlexTV 2.0!
