### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by eternistarr** [d8ahazard/Phlex#180]
On what OS are you running Phlex?
Windows 10

Are you using a new instance of XAMPP, or an existing webserver?
New instance of XAMPP

If Using an existing Webserver, have you ensured the proper modules are enabled and installed, and that PHP can read and write to the /Phlex directory?
I believe I have enabled all the modules by un commenting the below lines from the php.ini file
extension=php_sockets.dll

If you're having issues communicating with a specific instance of Plex/Couchpotato/Sonarr/etc. - tell me the OS you're running that app on.
N/A

Is Phlex using http or https?
http

There is extreme lag between issuing a command from google assistant or through web interface anywhere from 30 seconds to a few minuets. Google assistant times out and says flex tv isnt responding.
I have tried with and without my vpn. Have been unable to do the second linking of account for google assistant as it doesnt reply fast enough

Edit: Removed log info from public eyes...

**Comment by fopsdev** [comment]
maybe it helps if you delete the cookies from phlexchat.com and do the linking again

**Comment by eternistarr** [comment]
I have tried that, it also takes a very long time for phlexchat to respond for that. Sometimes it cant connect to me at all and other times it tells me that site is no longer available or has moved. canyouseeme.org can see my port open just fine.

**Comment by d8ahazard** [comment]
No, deleting the cookies won't do anything - that just stores your apitoken and server address while linking server.  It's updated every time you link.

However, figuring out why CURL can't access https://plex.tv would probably help you.  

Looks like the delay with everything is because it can't find your devices, which means it won't work, which is bad.  So, I force the app to keep trying to get data, just in case there's a *temporary* issue.  This issue is not temporary.

I'd suggest checking your firewall configuration on win10, make sure ports 80 and 443 are enabled for Xampp.  If the server can't talk on 80 and 443, it's not gonna have a good time.  

In fact, might be a good idea to just disable windoze firewall for Xampp entirely, as it also needs to bind to tcp for sockets/cast communication.  Personally, I just turn windoze firewall off entirely, but that's up to you.

Also, if you have a router or anything else that provides firewall access...make sure those are open.

**Comment by eternistarr** [comment]
I just tried it on a different computer, only thing I did different was disable UAC from regedit, Firewall was off completely on both pcs. Thanks for the help, its not ideal but this will work.

**Comment by d8ahazard** [comment]
Maybe instead, close xampp entirely, then try right-clicking and picking
"run as administrator" to launch it?
