### ISSUE TITLE
Config writing is spotty

### ISSUE THREAD

**Issue by teejo75** [d8ahazard/Phlex#185]
Writing to config.ini.php is not consistent.
If I modify settings within Phlex, for example, to enable both radarr and sonarr... only some of the settings get written to config.ini.php.

It will write all the profiles for both sonarr and radarr, and set the profile to 1 (any) despite that not being the selected profile. It will not write the IP/url for either of them.

Refresh the page, access settings again, and enter the missing stuff - tokens and IPs, but only the token will get written.

Refresh the page again, access settings, enter the missing info, and only the sonarr ip/url will be written.

**Comment by abrenoch** [comment]
I noticed this too. I did eventually get it to save the correct profile, but it took a few attempts.

Maybe having a dedicated 'update settings' button would be more reliable than updating them as they are changed?

**Comment by teejo75** [comment]
I had to manually edit the config to get my radarr auth token to stick. It wouldn't save no matter how many times I entered it.

**Comment by jvreeken** [comment]
Same for me... not saving settings.  It’s really frustrating.  I use sonarr and radarr and neither of the settings stick.

**Comment by abrenoch** [comment]
I know it sounds excessive, but after changing your radarr/sonarr settings, click 'test' after each time. If the test goes through, reload the page and confirm the settings stick.

I found myself changing a single setting and reloading to confirm it stayed.

ALSO - make sure your config.ini.php is editable per step 7 in the php install instructions in the readme! If your settings are not saving AT ALL your config file may not be writable by the user running php.

**Comment by teejo75** [comment]
@abrenoch done and done.
Every time I changed settings, I hit the test button, test successful. No settings written, except maybe one.
If the config.ini.php was not writable, then NO settings would get written at all, rather than one setting every now and then.
There definitely needs to be a save button. It just seems wrong not being able to ensure your settings are saved.

**Comment by d8ahazard** [comment]
@teejo75 

I guess I'm going to have to respectfully disagree with you there.  I've had this method in place of writing configs for quite a while now, and it's never been brought up.  

My suspicion is you guys possibly have something else going on in the background that is running and preventing configuration writing from being instantaneous...which it needs to be.

I don't like the idea of needing a "save" button.  It shouldn't be necessary.  I'd much rather try and figure out what the issue is for you guys, and fix it accordingly.

For example - do you guys turn your servers off?  If the app can't find a server, it's default behavior is to keep scanning.

If it's busy scanning for devices, then yes, there is going to be lag in doing other things, like saving the configuration data.

I guess what I can look at doing is moving the configuration saving stuff to another file, which would then mean device scanning happens independent of configurations...

But, if you guys could provide some logs of this lagging out, it would help me to confirm the issue.

**Comment by teejo75** [comment]
@d8ahazard 

My environment is live all the time. Phlex is running in a dedicated VM (Xenserver Host). The host is fairly idle. Lag is a possibility, however everything was pretty much idle while I was setting up Phlex.

I'm happy to provide you with logs, just tell me what you want to see.

**Comment by d8ahazard** [comment]
@teejo75 

This should be fixed now.  I've updated the writing mechanism so that the only time it calls any other functions is if you enable/disable cast (need to rescan devices) or for one other setting.

Also, I think I was accidentally declaring the listener for settings change every time the data for the page refreshed, meaning it'd try to fire the setting/save function potentially *hundreds* of times if you left Phlex UI open for a while.

Both of these should be fixed up, and tested, and fixed some more today.  Please give a whirl now, and close if you're satisfied.

**Comment by teejo75** [comment]
Looks good now! Thanks for fixing it!
