### ISSUE TITLE
Latest commit borked the config

### ISSUE THREAD

**Issue by teejo75** [d8ahazard/Phlex#187]
https://github.com/d8ahazard/Phlex/commit/6a00b67c7d5e01a7ce7ce20d9c0065467f635ccd

I noticed the new commit, so I reset my phlex install. For good measure, I re-cloned the repo.

On initial loading, I got the blank screen like in #176 however, fixed it by resetting cookies.

After submitting the login form, the 'One moment' notification stayed up permanently. Checking the phlex logs it says login was successful. I refreshed the page and got an error 500.

The apache error log entry:
```
[Fri Nov 10 09:01:30.040771 2017] [:error] [pid 6081] [client 192.168.1.10:54464] PHP Warning:  syntax error, unexpected '=' in config.ini.php on line 11\n
in /var/www/html/vendor/pear-pear.php.net/Config_Lite/Config/Lite.php on line 131
[Fri Nov 10 09:01:30.040817 2017] [:error] [pid 6081] [client 192.168.1.10:54464] PHP Fatal error:  Uncaught Config_Lite_Exception_Runtime: failure, can not parse the file: config.ini.php in /var/www/html/vendor/pear-pear.php.net/Config_Lite/Config/Lite.php:133\n
Stack trace:\n
#0 /var/www/html/vendor/pear-pear.php.net/Config_Lite/Config/Lite.php(891): Config_Lite->read('config.ini.php', 0)\n
#1 /var/www/html/util.php(872): Config_Lite->__construct('config.ini.php')\n
#2 /var/www/html/index.php(4): checkSSL()\n
#3 {main}\n
  thrown in /var/www/html/vendor/pear-pear.php.net/Config_Lite/Config/Lite.php on line 133
```

Looking at the newly written config.ini.php, this is what I get (sanitized):
(Note that I have replaced the actual strings with new strings, but they are repeated as they are in reality)
```
'; <?php die('Access denied'); ?>
[general]
deviceID = "afb085f344fd8345d160e85d7b653edc"

[user-_-user-_-PlexUser]
user-_-PlexUser = "139c3b6406622017d8b8185a5e3918ab"
PlexUser = "139c3b6406622017d8b8185a5e3918ab"
RANDOMSTRINGOFLETTERS = "139c3b6406622017d8b8185a5e3918ab"
email@address = "139c3b6406622017d8b8185a5e3918ab"
https://192.168.1.52//img/cache/4ec1c88b41987987ca039fcbcb0d8a36.jpeg = "139c3b6406622017d8b8185a5e3918ab"
ZZ9fd7102c427743c8dca1202232fc2cab== = "139c3b6406622017d8b8185a5e3918ab"
139c3b6406622017d8b8185a5e3918ab = "139c3b6406622017d8b8185a5e3918ab"
```

So the line 11 it's complaining about is the base64 encoded string on the second last line.

**Comment by teejo75** [comment]
Phlex_error.log
```
[10-Nov-2017 09:59:01 Australia/Melbourne] PHP Fatal error:  Uncaught Config_Lite_Exception_Runtime: failure, can not parse the file: config.ini.php in /var/www/html/vendor/pear-pear.php.net/Config_Lite/Config/Lite.php:133
Stack trace:
#0 /var/www/html/vendor/pear-pear.php.net/Config_Lite/Config/Lite.php(891): Config_Lite->read('config.ini.php', 0)
#1 /var/www/html/util.php(715): Config_Lite->__construct('config.ini.php')
#2 /var/www/html/api.php(370): checkSetDeviceID()
#3 /var/www/html/api.php(55): setSessionVariables()
#4 {main}
  thrown in /var/www/html/vendor/pear-pear.php.net/Config_Lite/Config/Lite.php on line 133
```
[Phlex.log](https://github.com/d8ahazard/Phlex/files/1459523/Phlex.log)

**Comment by d8ahazard** [comment]
Hello there, sorry to hear about this.

Please take a look at the contents of config.ini.php - it should look like
this:

'; <?php die('Access denied'); ?>
[user-_-digitalhigh]
plexToken = "BkBkBkBkBkBk444432"
plexEmail = "foo@gmail.com"
plexAvatar = "https://my.server.address/images/foo.jpg"
plexCred = "BKBKBKBKBKBKBKBKBkbkbkbk44923"
plexUserName = "digitalhigh"
apiToken = "010101010101010101010101010101010"
publicAddress = "http://my.server.address/"
couchEnabled = "true"
sickEnabled = "true"
sickAuth = "101010101010410110101010"
couchAuth = "101010101010410110101010"
couchIP = "https://couch.my.server.address"
couchPort = 443
couchProfile = "7177d4f7d6734900b891f263f4547662"
sickIP = "https://sick.my.server.address"
sickPort = 443
appLanguage = "en"
couchPath = ""

[general]
deviceID = "101010101010410110101010"
revision = "6a00b67c7d5e01a7ce7ce20d9c0065467f635ccd"


Important things to note:

The first line should be formatted exactly as shown.
No whitespace between the php die line and the user-_- line, or any other
lines except the last value in a section and the header for the next
section (between couchPath and [general].
Order of sections doesn't matter - so if general is above
[user-_-yourusername], no big deal.

You can delete entries for dList, mList, and the sickList, radarrList,
couchList, etc. arrays without issue, these are cache values to allow the
app to load faster.

Make sure not to change apiToken, otherwise you'll have to relink your
account with the mothership.


I'll add a feature that backs up the config file before installing updates,
just in case something silly like this happens again...

**Comment by Nowwis** [comment]
Hi,

I write here too because it's the same problem.

I want to start a new project.
My config.ini.php does not have a general section ...

Stack trace:
-  Notice: Undefined index: general in C:\Users\s.helene\Project\Test\Phlex\vendor\pear-pear.php.net\Config_Lite\Config\Lite.php on line 468

- Warning: array_key_exists() expects parameter 2 to be array, null given in C:\Users\s.helene\Project\Test\Phlex\vendor\pear-pear.php.net\Config_Lite\Config\Lite.php on line 468

My config.ini.php :
'; <?php die('Access denied'); ?>
[user-_-xxxxx]
publicAddress = "http://xxxxxxxxx/Phlex/"
dlist = "xxxxxxxxxxxxxxxx"
plexServerId = "xxxxxxxx"
plexServerProduct = "xxxxxxxxxx"
plexServerName = "xxxxxxxxx"
plexServerUri = "xxxxxxxxxxxx"
plexServerPublicUri = "xxxxxxxxxxx"
plexServerPublicAddress = "xxxxxxxx"
plexServerToken = "xxxxxxxxxxxx"

**Comment by d8ahazard** [comment]
Okay, you guys should be fixed up.  General section creation, proper saving
of userdata vars has been fixed.

**Comment by Nowwis** [comment]
OK good job!

I had to create the directory "logs" in the root directory otherwise function touch() does not work ! Closed for me !
