### ISSUE TITLE
PHP Fatal Error: Cannot parse the file: config.ini.php

### ISSUE THREAD

**Issue by Azuraxe** [d8ahazard/Phlex#188]
Hi,
I am trying to login for the first time, however I get the following error in the Phlex log!

[10-Nov-2017 10:39:35 UTC] PHP Fatal error:  Uncaught Config_Lite_Exception_Runtime: failure, can not parse the file: config.ini.php in /var/www/Phlex/vendor/pear-pear.php.net/Config_Lite/$
Stack trace:
#0 /var/www/Phlex/vendor/pear-pear.php.net/Config_Lite/Config/Lite.php(891): Config_Lite->read('config.ini.php', 0)
#1 /var/www/Phlex/util.php(715): Config_Lite->__construct('config.ini.php')
#2 /var/www/Phlex/api.php(370): checkSetDeviceID()
#3 /var/www/Phlex/api.php(55): setSessionVariables()
#4 {main}
  thrown in /var/www/Phlex/vendor/pear-pear.php.net/Config_Lite/Config/Lite.php on line 133

**Comment by d8ahazard** [comment]
Hello there, sorry to hear about this.

Please take a look at the contents of config.ini.php - it should look like
this:

'; <?php die('Access denied'); ?>
[user-_-digitalhigh]
plexToken = "BkBkBkBkBkBk444432"
plexEmail = "foo@gmail.com"
plexAvatar = "https://my.server.address/images/foo.jpg"
plexCred = "BKBKBKBKBKBKBKBKBkbkbkbk44923"
plexUserName = "digitalhigh"
apiToken = "010101010101010101010101010101010"
publicAddress = "http://my.server.address/"
couchEnabled = "true"
sickEnabled = "true"
sickAuth = "101010101010410110101010"
couchAuth = "101010101010410110101010"
couchIP = "https://couch.my.server.address"
couchPort = 443
couchProfile = "7177d4f7d6734900b891f263f4547662"
sickIP = "https://sick.my.server.address"
sickPort = 443
appLanguage = "en"
couchPath = ""

[general]
deviceID = "101010101010410110101010"
revision = "6a00b67c7d5e01a7ce7ce20d9c0065467f635ccd"


Important things to note:

The first line should be formatted exactly as shown.
No whitespace between the php die line and the user-_- line, or any other
lines except the last value in a section and the header for the next
section (between couchPath and [general].
Order of sections doesn't matter - so if general is above
[user-_-yourusername], no big deal.

You can delete entries for dList, mList, and the sickList, radarrList,
couchList, etc. arrays without issue, these are cache values to allow the
app to load faster.

Make sure not to change apiToken, otherwise you'll have to relink your
account with the mothership.


I'll add a feature that backs up the config file before installing updates,
just in case something silly like this happens again...

**Comment by horvath** [comment]
Having this issue as well. There was no config.ini.php file in my Phlex folder.

Here's the error I'm getting:

Warning: file_put_contents(config.ini.php): failed to open stream: Permission denied in /Applications/XAMPP/xamppfiles/htdocs/Phlex/vendor/pear-pear.php.net/Config_Lite/Config/Lite.php on line 270
Exception Message: failed to write file `config.ini.php' for writing.
Warning: file_get_contents(/Applications/XAMPP/xamppfiles/htdocs/Phlex/config.ini.php): failed to open stream: No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/Phlex/util.php on line 488

Warning: file_put_contents(/Applications/XAMPP/xamppfiles/htdocs/Phlex/config.ini.php): failed to open stream: Permission denied in /Applications/XAMPP/xamppfiles/htdocs/Phlex/util.php on line 489
