### ISSUE TITLE
Radarr Test Passes but fails to find movies

### ISSUE THREAD

**Issue by eternistarr** [d8ahazard/Phlex#190]
The Radarr Test Passes but it doesn't pull the profiles like sonarr does.  When movies are requested they come back as failed to find. Checked Radarr and searched for movie there and is found.

On what OS are you running Phlex?
win 10
Are you using a new instance of XAMPP, or an existing webserver?
xampp
If Using an existing Webserver, have you ensured the proper modules are enabled and installed, and that PHP can read and write to the /Phlex directory?
yes
If you're having issues communicating with a specific instance of Plex/Couchpotato/Sonarr/etc. - tell me the OS you're running that app on.
windows 10 Radarr isnt working Sonarr works great
Is Phlex using http or https?
[Phlex.log](https://github.com/d8ahazard/Phlex/files/1462999/Phlex.log)

**Comment by jneljeff** [comment]
I am experiencing the same issue.  Sonarr works great, but Radarr isn't getting anywhere despite the connection testing fine.

[Phlex.log](https://github.com/d8ahazard/Phlex/files/1471386/Phlex.log)

**Comment by eternistarr** [comment]
I was able to get i to work but I had to sign in as a different user with the same plex account and setup Radarr then it worked fine on both accounts

**Comment by jneljeff** [comment]
@eternistarr could you elaborate on that?  Sign in with different what account?

**Comment by eternistarr** [comment]
So for instance I used my daughters shes added in plex under users/friends she has an email address that my plex server is shared to. I logged in with her email address and then setup Radarr and it worked then logged out and signed back into the main account and then it worked. Its definitely something to do with Phlex not grabbing the profile from Radarr. Once that showed up it started working just fine. Hope that makes sense

**Comment by jneljeff** [comment]
A worth while effort, but I had no such luck with that trick.  I did notice that the API key for Radarr was gone after setting it in another Plex account.  I reconfigured under my own account and still no dice.  Same result and logs.

**Comment by halethrain** [comment]
I'm having the issue as well. Running develop branch of radarr

Radarr debug log:
17-11-30 15:18:53.7|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (11 ms)
17-11-30 15:18:53.9|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (6 ms)
17-11-30 15:18:54.1|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (6 ms)
17-11-30 15:19:09.2|Debug|Api|[GET] /api/calendar?start=2017-10-31&end=2017-12-30: 303.SeeOther (0 ms)
17-11-30 15:19:09.2|Debug|Api|[GET] /api/calendar?start=2017-10-31&end=2017-12-30: 200.OK (16 ms)
17-11-30 15:19:10.6|Debug|Api|[GET] /api/rootfolder: 303.SeeOther (0 ms)
17-11-30 15:19:10.7|Debug|RootFolderService|Generating list of unmapped folders
17-11-30 15:19:10.9|Debug|RootFolderService|7 unmapped folders detected.
17-11-30 15:19:10.9|Debug|RootFolderService|Generating list of unmapped folders
17-11-30 15:19:11.1|Debug|RootFolderService|3 unmapped folders detected.
17-11-30 15:19:11.1|Debug|Api|[GET] /api/rootfolder: 200.OK (409 ms)
17-11-30 15:19:11.1|Debug|Api|[GET] /api/movies/lookup?term=to+kill+mockingbird: 303.SeeOther (0 ms)
17-11-30 15:19:11.1|Debug|Parser|Parsing string 'to kill mockingbird'
17-11-30 15:19:11.1|Debug|Parser|Unable to parse to kill mockingbird
17-11-30 15:19:11.5|Debug|Api|[GET] /api/movies/lookup?term=to+kill+mockingbird: 200.OK (393 ms)
17-11-30 15:19:11.5|Debug|Api|[GET] /api/movie: 303.SeeOther (0 ms)
17-11-30 15:19:11.7|Debug|Api|[GET] /api/movie: 200.OK (196 ms)
17-11-30 15:19:11.9|Debug|Api|[POST] /api/movie: 303.SeeOther (0 ms)
17-11-30 15:19:12.1|Debug|Api|[GET] /api/movie: 200.OK (188 ms)
Phlex log:
Add result: 
{
  "title": "To Kill a Mockingbird",
  "alternativeTitles": [],
  "secondaryYearSourceId": 0,
  "sortTitle": "to kill mockingbird",
  "sizeOnDisk": 0,
  "status": "released",
  "overview": "In a small Alabama town in the 1930s, scrupulously honest and highly respected lawyer, Atticus Finch puts his career on the line when he agrees to represent Tom Robinson, a black man accused of rape. The trial and the events surrounding it are seen through the eyes of Finch's six-year-old daughter, Scout. While Robinson's trial gives the movie its momentum, there are plenty of anecdotal occurrences before and after the court date: Scout's ever-strengthening bond with older brother, Jem, her friendship with precocious young Dill Harris, her father's no-nonsense reactions to such life-and-death crises as a rampaging mad dog, and especially Scout's reactions to, and relationship with, Boo Radley, the reclusive 'village idiot' who turns out to be her salvation when she is attacked by a venomous bigot.",
  "inCinemas": "1962-12-25T00:00:00Z",
  "images": [
    {
      "coverType": "poster",
      "url": "http://image.tmdb.org/t/p/original/2lgU2AmCcLDTIyXIjjFgAxjdtBH.jpg"
    }
  ],
  "downloaded": false,
  "remotePoster": "http://image.tmdb.org/t/p/original/2lgU2AmCcLDTIyXIjjFgAxjdtBH.jpg",
  "year": 1962,
  "hasFile": false,
  "profileId": 0,
  "pathState": "dynamic",
  "monitored": false,
  "minimumAvailability": "tba",
  "isAvailable": true,
  "folderName": "",
  "runtime": 0,
  "tmdbId": 595,
  "titleSlug": "to-kill-a-mockingbird-595",
  "genres": [],
  "tags": [],
  "added": "0001-01-01T00:00:00Z",
  "ratings": {
    "votes": 729,
    "value": 8
  },
  "qualityProfileId": 0
}

{
  "status": "ERROR: Error adding title to searcher."
}

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
