### ISSUE TITLE
IFTTT calls to api.php should be non-blocking

### ISSUE THREAD

**Issue by msh100** [d8ahazard/Phlex#20]
I appreciate that's not so simple in PHP, however there's not much in terms of error capturing anyway so the fact api.php can block on long requests making them longer than they need to be causes issues on IFTTT. I think IFTTT is timing out for mine and sending retries? whatever is happening it feels sluggish and there is sometimes weird behaviour.

I have resolved this by adding a nonblocking request proxy in NodeJS. I guess something like this should be documented (as IFTTT can not error handle anyway) or some queuing needs to be implemented.

Below is my Node app for reference:

```javascript
var express = require('express');
var app = express();
var request = require('request');

app.get('*', function (req, res) {
    res.send('Request Sending');

    request('http://127.0.0.1:8585/' + req.url, function (error, response, body) {
        console.log('statusCode:', response && response.statusCode);
    });
})

app.listen(8686)
```

**Comment by d8ahazard** [comment]
What if I update the methods curlGet and CurlPost to use this library:

https://github.com/stil/curl-easy

I haven't researched it a ton yet, but it looks promising...

**Comment by msh100** [comment]
Well regardless of what changes PHP side, it will still have to block somehow until the requests are all complete otherwise execution will be killed.

In my example above the request to PHP will continue even after the client has been given its result.

**Comment by d8ahazard** [comment]
Been doing more research on this, because it bugs the crap out of me.  I may be able to use something like this to do calls in an async fashion:

  <?php

  /*
   * This is the process being called. From here,
   * we'll launch child process child.php
   */

  // open child process
  $child = fopen('http://'.$_SERVER['HTTP_HOST'].'/child.php', 'r');

  /*
   * Do some work, while already doing other
   * work in the child process.
   */

  // get response from child (if any) as soon at it's ready:
  $response = stream_get_contents($child);

By creating a new parent .php file that IFTTT can fire commands at, and then passing those commands to api.php, I should be able to avoid blocking all execution.  It's not the best solution, but it's what I'm going to try...

**Comment by msh100** [comment]
Within pure PHP, the process **has** to continue blocking until all children have exited.

**Comment by d8ahazard** [comment]
Agreed that with PHP, it cannot be, without pthreads or another alternative that would require too much setup on the user's part.  I've tried running as background via both OS's, and a bajillion different tricks, but it never winds up being truly non-blocking.

The best I can do is better caching of the device lists, which is really where all of the hangups occur, for the most part.  This has been extensively reworked, and the cast discovery mechanism tuned to be more reliable and faster.  

As such, this becomes mostly a philosophical discussion until I decide to recode to a language that supports async processing in a non-blocking fashion.  I've done what I could, it should be pretty tolerable now.
