### ISSUE TITLE
Use the current plex server address for sending media to a playback device rather than parsing the device's indicated connections

### ISSUE THREAD

**Issue by abrenoch** [d8ahazard/Phlex#206]
Its a bit late, so please let me know if this isn't making sense!

I'm still fiddling with PlexKodiConnect, and did manage to make it work with phlex, although after some code modifications.

Basically it looks like phlex is looking for `<Connection>` elements within each playback device returned via the plex API, but strangely enough PKC is not supplying that information (https://github.com/croneter/PlexKodiConnect/issues/363). However, looking at my api responses from plex, they all appear to point at my server's IP address anyway. Considering the playback targets are defined via the `X-Plex-Target-Client-Identifier` variable (when sent to the server), can't we just use that as a fallback when no connections are listed? I only have my one server so I'm not sure how this would interact with more complex setups...

So I was able to get PKC working correctly by bypassing the client connection checks in `scanDevices` and then just using `$_SESSION['plexServerUri'];` for each device's uri property (I did move the session variable setting block above the `foreach ($devices['clients'] as $device)` loop to get the current server).

I hope this helps in some way, this also got plex on my phone listed as a possible playback device as well (for better or worse I suppose) - which did have a `<Connection>` listed strangely but would not list in the playback targets.

**Comment by d8ahazard** [comment]
Hmmm...I wonder if they've updated something to allow triggering of remote
playback from outside the LAN.  Although it could be that I've been sending
duplicate target-client-identifier headers as well, which was just fixed.

Given the vast amount of client-related issues that are open, I'm highly
considering revisiting the scanning and playback mechanisms to allow
stronger caching of devices, as well as see about not requiring a local
client in order to play media to Plex players.  If that were the case, then
it's possible I could do everything from one website, barring people who
want to use casting...

**Comment by d8ahazard** [comment]
They HAVE! And this discovery triggered the entire current phase of development, working towards the V2 release. 

You can follow the app's progress via the /beta branch, but be aware that this is a WIP until moved to the main branch.  :D
