### ISSUE TITLE
Undefined variable: _SESSION in C:\xampp\htdocs\phlex\util.php on line 365

### ISSUE THREAD

**Issue by The1Authority** [d8ahazard/Phlex#240]
I installed Phlex fresh and I get this error, not much seem's to work.
I can't see anything in the log (web interface). The API test link is not working (failed) but in the Phlex.log it's indicated as successful. Can't find my chromecast either. Some time I get the error 3 time in a row, some time I dont.

**Comment by mmnaseri** [comment]
I suspect you might have the wrong version of PHP. But without knowing more it is hard to say.

**Comment by The1Authority** [comment]
I downloaded the last version of xampp today. Have php 7.1.1 I think

**Comment by mmnaseri** [comment]
I have `7.0.19` and this is working fine. Can you create a file in your `C:\xampp\htdocs\` as `info.php` with the following content:

```php
<?php
phpinfo();
?>
```

Then go to your http://localhost/info.php (assuming port `80`, otherwise use the port you are on), and check to see if under **session**: 

1. *Session Support* is enabled, and
2. `session.save_path` points to a folder on your computer that actually exists.

If either of those is the issue, you need to fix it.

**Comment by d8ahazard** [comment]
Fixed with 28d8470.
