### ISSUE TITLE
Remote Client?

### ISSUE THREAD

**Issue by spencercharest** [d8ahazard/Phlex#245]
Hi, I've searched for an answer to this and could not find anything. Is it possible to host Plex and Phlex on a remote server and play on a local client? I did some fishing and found the port that my client runs on and opened the port. I tried to add the client in the "static devices" field using my outward facing IP and port number (which I can ping) but the device does not show up in the devices field. Am I misunderstanding the point of "static devices"? Is this possible currently?

**Comment by d8ahazard** [comment]
Hi,

As far as I know, this is not possible. Phlex is designed to be run on the same LAN as a player. While it may technically be possible to do what you want to do, I'm not entirely sure what would be required in the port forwarding department in order to accomplish this.

The "Static Devices" section is designed for users who's players aren't detected 100% of the time so they can statically define them. You can also rename devices this way if you don't want to rename them on themselves.
