### ISSUE TITLE
Feature Request: Add configurable synonyms for TV Shows

### ISSUE THREAD

**Issue by salimnanji** [d8ahazard/Phlex#295]
Set this up a few days ago, so far so good. I have a few requests I think would be useful:

1. Allow synonyms for TV shows. If I tell google "Watch the latest episode of agents of shield", it can't find anything because it's looking for "agents of shield" rather than "agents of s.h.i.e.l.d.". If I can configure some of these edge cases manually (e.g.  #agents of shield -> agents of s.h.i.el.d.), life would be much easier

2. Turn on auto-update by default, or show the auto-update toggle at all times in settings. When I first installed, There wasn't see any autoupdate function visible, so I built a quick script to pull from github. I only saw the toggle when updates were available.

**Comment by d8ahazard** [comment]
1. That's tough.  There are so few cases like this, that at this point in time at least, it'd be a distraction from other things I want to work on. What I'd suggest is - and I just tried this - go into *Plex* and edit the show.

In the blank "Original Title" field, just put in "Marvel's Agents of SHIELD". 

Bam, comes up in the search hub, which means Phlex will find it no problem.

I know it's not ideal, but the issue is really with Google not parsing the name right. 

2. Auto-update shows up when it detects Phlex has been cloned from git. I think when you did your git pull script, you turned it into a git directory, and then it shows up.

Auto-updating without having git is a pain in the butt, and not something I'll be implementing either.

Hope this helps.
