### ISSUE TITLE
phlex help command loop

### ISSUE THREAD

**Issue by aberrix** [d8ahazard/Phlex#308]
When I asked "Okay google, ask flex tv help" to get a list of commands to get the "below are some suggestions you can try" it starts listing commands and gets to "cancel" and then it responds to itself(?) and stops, says it didn't catch what I said and then starts listing the commands over again, and gets caught in the same spot in a never ending loop.

**Comment by bobpaul** [comment]
This sounds like expected behavior. It's stopping because it hit the end of the list, not because it said the word cancel. You can't even give it any commands while it's rattling off its list. Try saying "Stop" or "Cancel" while Phlex TV is talking... nothing happens.

Phlex TV lists some example commands
Cancel is the last command in the list of examples. 
It then listens for you to give a command. (Now you can talk!)
You don't say anything, it says "I didn't catch that". If you said something, it would respond to what you said.

**Comment by aberrix** [comment]
The problem is it does not stop to listen for a command after it just then endlessly loops itself, it does not stop to prompt me, it gets to cancel and then starts over. This doesn’t seem like expected behavior.

**Comment by d8ahazard** [comment]
This is just weiiiird, and not something I can replicate. 

Maybe an odd question, but...does your voice sound like the assistant voice you're using for google? I can't think of any other good reason where it'd get stuck in a loop talking to itself...

**Comment by bobpaul** [comment]
The pull request implements the last suggestion.

**Comment by aberrix** [comment]
yeah, that seems to have fixed it - everything works as I would expect it. thanks!
