### ISSUE TITLE
Phlex TV is not responding, try again later

### ISSUE THREAD

**Issue by Sman42** [d8ahazard/Phlex#442]
#### 1. Are you hosting your own version of Flex TV, or using the one at https://app.phlexchat.com?
Hosting

#### 2. On what OS are you running Flex TV?
Windows 10 Pro 1803

#### 3. Are you using a new instance of XAMPP, or an existing webserver?
New instance

#### 4. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Flex TV?
Yes and Yes

#### 5. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes

#### 7. What are the last six digits of your server's API Token? (Settings -> Flex TV)
8c49a6

#### 8. Please describe the issue.

When giving commands to google home, Phlex tv will play the requested media, but the google assistant will say "Phlex TV is not responding, try again later".

**Comment by Dave-Still** [comment]
Same issue here on both Windows 7 and Pi deployment. Redeployed XAMPP in case.
Notice XAMPP php error log reporting repeating lines for each request:-

[19-Feb-2019 15:05:48 Europe/London] PHP Warning:  session_start(): Failed to read session data: files (path: E:\xampp\tmp) in E:\xampp\htdocs\Phlex\api.php on line 27
[19-Feb-2019 15:05:50 Europe/London] PHP Warning:  session_start(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in E:\xampp\htdocs\Phlex\api.php on line 27
[19-Feb-2019 15:05:50 Europe/London] PHP Warning:  session_start(): Failed to read session data: files (path: E:\xampp\tmp) in E:\xampp\htdocs\Phlex\api.php on line 27

**Comment by joshmckinney** [comment]
I've got the same thing as well. @Dave-Still called it. Line 27, function session_start() doesn't like what's going on.

Raspbian Server:
Warning:  session_start(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in /var/www/html/Phlex/api.php on line 27

**Comment by Dave-Still** [comment]
Addendum if this helps in the current diagnosis. On the Pi, the error is only reported as above if "display_startup_errors" is set to on in the php config:-

; The display of errors which occur during PHP's startup sequence are handled
; separately from display_errors. PHP's default behavior is to suppress those
; errors from clients. Turning the display of startup errors on can be useful in
; debugging configuration problems. We strongly recommend you
; set this to 'off' for production servers.
; Default Value: Off
; Development Value: On
; Production Value: Off
; http://php.net/display-startup-errors
display_startup_errors=On

 Otherwise Phlex defaults to "Phlex TV is not responding, try again later"
