### ISSUE TITLE
Local servers is not available error

### ISSUE THREAD

**Issue by bardiakeyvani** [d8ahazard/Phlex#48]
Phlex shows my local Playback server, but when I run the test it  errors that its not available. All the remote servers pass the test. I have a plex plus account and I can play everything from outside or locally. Any idea what I can be doing wrong?

**Comment by d8ahazard** [comment]
As the stereotypical adage goes - "It's not you, it's me.".  Give a pull of today's commit, let me know if it it helps.  I've added a method that checks the URL of each device before adding it to the list, hopefully, this should help exclude invalid or nonworking URL's for your server.

**Comment by AR1972** [comment]
I had the same issue, for me it turned out to be a DNS issue. Plex sends something that looks like this in its device list "192-168-1-6.e117334b90e44e2de4bf4f911814150c.plex.direct" which doesnt resolve to an IP address on my local network, I experimented with 3 work arounds

1. edit config.ini.php with the IP address of your server 

2. add a custom server access URL on the Plex server network configuration page that will resolve to the Plex servers IP address "http://plex.mydoamin.net" 

3. add a domain and host override in the DNS of your router host = "192-168-1-6" domain = "e117334b90e44e2de4bf4f911814150c.plex.direct"

**Comment by d8ahazard** [comment]
This should be fixed with commit 5a32304 - I've added a bit to generate a "fallback URI" in the event the plex.direct URI doesn't resolve for whatever reasons...
