### ISSUE TITLE
"Recaching due to missing data", over and over.

### ISSUE THREAD

**Issue by guice** [d8ahazard/Phlex#50]
Here's what I see in Phlex's logs:

```
Edited: Personal data removed, I know the issue.

~My Phlex site is in an infinite loop, causing dramatic slowness.~ Sorry, this isn't looping. This is from the constant ajax requests from the site code; It's DOS'ing itself...

**Comment by christopherbruce** [comment]
You should edit this to obscure your IP address and Plex Token

**Comment by d8ahazard** [comment]
Edited - I'm aware of the problem.  

I'll be pushing an update today that does several things for the device caching:

1.  Allows a user-customizable time delay between device refreshes.
2.  Add a counter to the re-cache so that it doesn't continuously loop if clients/servers can't be found.
3.  Add a manual "refresh devices" button.
4.  Try to further reduce the overhead caused by device scans/checking, etc.

**Comment by guice** [comment]
Awesome. Thanks for the update! I'll keep an eye out for it. :)

**Comment by d8ahazard** [comment]
@guice - Please give a pull and try now, I think I've made the device scanning a lot cleaner than what it had been doing.

**Comment by guice** [comment]
Phlex server appears to be going much more smoothly now. Thanks!
