### ISSUE TITLE
Parse error: syntax error, unexpected

### ISSUE THREAD

**Issue by exhibitO** [d8ahazard/Phlex#72]
Just did a gitpull to update, now I get there error when I launch Phlex in browser.

Parse error: syntax error, unexpected '?' in C:\xampp\htdocs\phlex\util.php on line 12

Something in this Function is broken. 

> function checkSetApiToken($userName) {
> 		// Check that we have generated an API token for our user, create and save one if none exists
> 		$config = new Config_Lite('config.ini.php');
> 		$apiToken = false;
> 		foreach ($config as $section => $user) {
> 		    if ($section != "general") {
> 		    	if (($userName == urlencode($user['plexUserName'])) || ($userName == urlencode($user['email']))) {
> 		    		write_log("Found matching token for user ".$user['plexUserName']);
>                     $apiToken = $user['apiToken'] ?? false;
>                     break;
>                 }
>             }
> 		}

**Comment by d8ahazard** [comment]
Update php to v7.

**Comment by eddiezab** [comment]
If you're running on some raspberry pi distros such as raspbian, php7 isn't in the repos at this time.

**Comment by d8ahazard** [comment]
@eddiezab - I can appreciate that requiring PHP7 may make it more difficult for some users to enjoy Phlex, a quick glance around the web tells me that it's still *possible* to install PHP7 on those distros with a bit of work.  

I don't want to alienate any users, but my primary focus when coding is to add the best level of support and performance for as many people as possible.  The requirement for PHP7 is not *just* because I like type coalescing and spaceship comparators, but because some of the underlying support libraries I use require it as well.

**Comment by d8ahazard** [comment]
https://www.stewright.me/2016/03/turn-raspberry-pi-3-php-7-powered-web-server/

**Comment by KrunchMuffin** [comment]
I am having this same issue but with 7.2.3. Too new?
