### ISSUE TITLE
Flex TV isn't responding right now...

### ISSUE THREAD

**Issue by techiezealot** [d8ahazard/Phlex#77]
Since install the response from Phlex have been laggy at best (took 5 minutes to play a film) or completely non-responsive.

I'm using XAMPP running on my main PC and Plex is installed on a QNAP device.

On what OS are you running Phlex?
Win10

Are you using a new instance of XAMPP, or an existing webserver?
XAMPP

If Using an existing Webserver, have you ensured the proper modules are enabled and installed, and that PHP can read and write to the /Phlex directory?
N/A

If you're having issues communicating with a specific instance of Plex/Couchpotato/Sonarr/etc. - tell me the OS you're running that app on.
QNAP TS-459 Pro / Plex

Is Phlex using http or https?
http

 I have also sent some details to the email address you provided with this issue number as the subject line.

Thanks!

**Comment by jfjallid** [comment]
I have noticed the same behaviour with my Phlex installation. It is unresponsive from the web gui and sometimes the action happens after a couple of minutes. When accessing Phlex from my Google Home I get the response that Flex TV isn't responding right now.

I'm running phlex in the docker build supplied by d8ahazard. 
I'm running Plex in a docker container aswell: plexinc/pms-docker. 
I'm accessing Phlex over https.

**Comment by d8ahazard** [comment]
@techiezealot @jfjallid  - I've done a bit of work on the cast stuff in the past few weeks, has this helped resolve your speed issues?  

If not - are either of you by chance trying to talk to a Plex Cloud Instance?  

Also - please let me know what type of player you are trying to control.  

Thanks!

**Comment by volkovolkov** [comment]
Hey there,

I am also having the same issue on the latest build. Adding new shows/TV to radarr/sonarr work fine, but if I tell it to play something, it will take 5-10 minutes before it plays, and phlex is then unreponsive. It will have a 504 error in the web interface and constant loop of Google Home telling me the command is taking longer than normal to execute, even after the TV show is playing.

Debug info:
Latest master branch installed
Ubuntu 14.04 LTS
nginx
php7-fpm with all necessary modules installed
php-fpm has no errors in its log, but its the service I have to restart to get phlex working again.

Tue, 27 Jun 2017 **12:59:27** -0600 [ DEBUG ] api.php::fetchInfo - We have a winner.  Title is 103 **(at this point, phlex is unresponsive)**
Tue, 27 Jun 2017 13:01:35 -0600 [ ERROR ] util.php::checkRemoteFile - Failure finding remote file.
Tue, 27 Jun 2017 13:01:35 -0600 [ DEBUG ] util.php::cacheImage - Function fired, caching https://123-123-123-123.xxxxxxxxxxx.plex.direct:32500/library/metadata/XXXX/thumb/123123123123?X-Plex-Token=XXXXXX
root@server:/opt/phlex/Phlex# tail -100 /opt/phlex/Phlex/Phlex.log
Tue, 27 Jun 2017 **13:05:50** -0600 [ ERROR ] util.php::checkRemoteFile - Failure finding remote file.
Tue, 27 Jun 2017 13:05:50 -0600 [ DEBUG ] util.php::cacheImage - Function fired, caching https://123-123-123-123.xxxxxxxxxx.plex.direct:32500?X-Plex-Token=XXXXX
Tue, 27 Jun 2017 13:05:50 -0600 [ DEBUG ] api.php::returnSpeechV1 - Final Speech should be: Okay, Playing the episode of XXX named 103. **(this is when the episode starts playing)**

--

Please let me know if you need any additional information. Thanks for making this awesome app.

**Comment by volkovolkov** [comment]
Also I should note, after the show starts playing, phlex becomes responsive again.

**Comment by d8ahazard** [comment]
@volkovolkov - I've added a new toggle to settings to disable plex.direct URL's, which may be the source of some of your issues.  Please give a try and let me know if toggling it helps at all.

**Comment by jfjallid** [comment]
@d8ahazard - The unresponsiveness from the GUI seems to be gone, nice work!
I am trying to control a chromecast 2nd generation.

I am not trying to use plex cloud and I found that the only way for me to get it to work is by manually putting the correct IP in the config.ini.php file for plexServerUri
Because I am running my Plex server on a machine with docker containers, Plex seems to advertise the docker ip addresses 172.17.0.1 and 172.18.0.1 as well as the correct server ip. I am guessing that only one of all the ip addresses advertised by the Plex server is tested and used by Phlex and that the wrong ip addresses are first in the list and thus preferred.

**Comment by jonfairbanks** [comment]
I am also having this issue. The FlexTV UI shows that everything was successful (from JSON -> "status": "success") but Google Assistant says "not available right now". 

Starting something from the UI starts very slow, then says it's playing successfully according to the JSON, but nothing happens on the device. If I start something in Plex normally however, it shows the current status in the Flex UI.  

Account Link: Google Assistant
Install Type: Unraid Docker
Playback Device: Nvidia Shield (Android TV)

**Comment by fastwagn** [comment]
I too am having the same issue stated by jonfairbanks.

I'm also having a problem with it connecting to Plex Media Player. I can't even get PMP to come up in player to control.

**Comment by fopsdev** [comment]
same here getting: "not available right now" when using via google assistant. playing from ui works

**Comment by mingersoll** [comment]
+1. Getting 'Flex TV isn't responding right now' on the Google Home. 

Looking at the code/logs it appears that the API key is being recreated even though it's in my config file? 

I did have to reinstall so I may have some session/global keys kicking around that might be screwing things up.

Playing from the UI is fine though.

**Comment by cdauria** [comment]
I'm getting the same issue, same setup.  It used to work for me but something happened.  I had to change the public address at one point and that got it working again.  Then I had to do a reset on my router so I don't know if that messed with port forwarding.  Log says couldn't validate user, invalid API token.  I tried looking up my token a different way (viewing XML through Plex, is this the proper method?) and tried that but no luck.  I'm not sure if it's Plex being linked to a different Google account now or what.  

Not sure if related but I was unable to edit the API token on the web UI, when trying to edit config.ini.php through XAMPP I get the error cannot find the path specified.  I was able to find the ini though and edit it in order to change the API token.

Web UI response is ""I couldn't find  bad mom  in your library. Should I try to add it to the watch lists?" 
Is there some way I can reset everything and start over without messing things up further?  I can share logs or if possible perhaps I can get some help through TeamViewer or something because I'm really lost and I miss this functionality.

**Comment by d8ahazard** [comment]
Hi, thanks for the feedback.

This issue has either been fixed in the current /beta branch, or is slated for revisal/revision in the forthcoming V2 release.

As such, I'll be closing this issue to help focus on outstanding issues and features yet to be addressed in the new codebase.

Feel free to follow the progress in the /beta branch, and be sure to get set up by adding the new cast plugin to your local Plex server.

https://github.com/d8ahazard/Cast.bundle

Keep an eye on the forum for the release of FlexTV 2.0!

**Comment by voxware** [comment]
Thanks, I actually fixed my issue by saving my config.ini.php
(config.inc.php) and reinstalling xampp as well as phlex.  everything works
great now, looking forward to future developments.

Take care, great work.
