### ISSUE TITLE
Feature Request: Shuffle and Unwatched Key Words

### ISSUE THREAD

**Issue by damijares** [d8ahazard/Phlex#80]
Hi,

First of all, thanks for the amazing work that you are doing on making my G-Home useful.

I got couple of ideas that I think that could improve the over all experience,  please let me know if I missing something.

* **Shuffle** TV show episode, "**Shuffle** Family Guy" or "Play **Random** episodes of _The Simpsons_ **Season 4**" . Also, It can be done with movies with some specific actor or genre (I know there is a similar command for this, but it doesn't work with TV shows the same way), "Play<random/shuffle/aleatory> animated movie"
* Being able to use "**Unwatched**" for filtering, "Play **unwatched** episodes", "Play **unwatched** episodes of _Game of Thrones_"
* Playing everything on deck, "Play (on)deck", "Play what's on deck"  

These are the dream request
* resuming what whatever is in progress on deck 
* queuing items on the current playlist

**Comment by d8ahazard** [comment]
I've kinda already beat you to the punch on most of these!  :D 

Try:

"Play a random episode of Family Guy":  Self explanatory.

"Play Game of thrones" - play the first unwatched episode of a series.  Basically, I'm going to assume that you want to watch the first unwatched episode if it exists, and if you do, that you'll want to start out where you left off (if you stopped it 15 minutes in, say)

"resume" - Just tell it to play what you want, as described above.  

"Shuffle" is a good one - I'll have to sniff out that command and implement it, but shouldn't be too tough to do.  

Play everything on-deck might be a bit tougher, simply because I don't have any "put a bunch of stuff to a playlist" functions written yet.  Not impossible, I just don't have any code written already or research done on the steps required.  

Queueing things to a playlist - same as above.  

I'll keep this open for the other stuff, but give a try for the ones I mentioned.

**Comment by damijares** [comment]
Thanks so much for your reply.

 I'll try this and let you know.

**Comment by kevinmclane** [comment]
I second the request for shuffle.  One of my favorite things to do is put my music library on shuffle and cast it.  Thanks again for putting this together

**Comment by mtompkins** [comment]
Great app -- and PaLease +1 Shuffle!!

**Comment by d8ahazard** [comment]
Shuffle keyword is in the works for V2, as is "unwatched".

![image](https://user-images.githubusercontent.com/1633844/36009987-a60f1be2-0d14-11e8-8e08-ee37f01fb716.png)
