### ISSUE TITLE
Image isn't using Plex URL

### ISSUE THREAD

**Issue by kylerw** [d8ahazard/Phlex#9]
Error loading image:

https://phlex.mydomain.com/library/metadata/35253/art/1487349280

when it should be

http://plex.host.tv:port/library/metadata/35253/thumb/1487349280

**Comment by d8ahazard** [comment]
Phlex uses an image caching system to store stuff displayed in the WebUI (Otherwise you can get loading issues if you're behind a firewall that doesn't allow random ports).  

This appears to be an issue of that system not working.  I've made some changes to this in the past few days, could you please update and give a try when you have time?

**Comment by kylerw** [comment]
That appears to have resolved this issue
