### ISSUE TITLE
Export a Copy of Api.ai Agent

### ISSUE THREAD

**Issue by waterapi** [d8ahazard/Phlex#94]
Hi,

I really like your application and want to study it.
Would it be possible to open source your API.ai agent by exporting it and putting it in git?

<img width="704" alt="screen shot 2017-07-02 at 6 46 48 am" src="https://user-images.githubusercontent.com/29823690/27765360-4935d3dc-5ef2-11e7-9cec-51937c3da575.png">
<img width="634" alt="screen shot 2017-07-02 at 6 06 32 am" src="https://user-images.githubusercontent.com/29823690/27765361-4faa53dc-5ef2-11e7-8415-53f770c6f270.png">

**Comment by d8ahazard** [comment]
With all due respect...I'd prefer not to.  The public code behind Phlex is a pretty good indicator at how I'm making it work - if you look at the function parseApiCommand(), you'll see how I'm parsing out most of the sauce there.  

Reasons for not wanting to share everything are simply because the agent *is* a lot of what makes Phlex work, and should I ever choose to monetize any aspect of the service I've created, *not* having the code for the API.ai agent out there in the wild will be instrumental to preventing others from circumventing any system I could put in place to help with said monetization.

So, if you have questions, I'd be happy to discuss privately with you what I've done, but I would prefer to keep the agent bit to myself.  Sorry.
